# Generated by Django 2.0.3 on 2024-04-01 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allocate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cart_quantity', models.BigIntegerField()),
                ('Cart_price', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cmplnt', models.CharField(max_length=200)),
                ('Cmplnt_date', models.CharField(default=1, max_length=200)),
                ('Cmplt_reply', models.CharField(max_length=200)),
                ('Reply_date', models.CharField(default=1, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_name', models.CharField(max_length=200)),
                ('C_email', models.CharField(max_length=200)),
                ('C_phn', models.BigIntegerField()),
                ('C_place', models.CharField(max_length=200)),
                ('C_post', models.CharField(default=1, max_length=200)),
                ('c_pin', models.CharField(default=1, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_name', models.CharField(max_length=200)),
                ('E_image', models.CharField(max_length=200)),
                ('E_address', models.CharField(max_length=200)),
                ('E_phn', models.BigIntegerField()),
                ('E_email', models.CharField(max_length=200)),
                ('gender', models.CharField(default=1, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('usertype', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('O_date', models.DateField()),
                ('o_time', models.CharField(max_length=200)),
                ('O_status', models.CharField(max_length=200)),
                ('CUSTOMER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pay_type', models.CharField(max_length=200)),
                ('Pay_status', models.CharField(max_length=200)),
                ('pay_date', models.CharField(default=1, max_length=200)),
                ('pay_amount', models.CharField(default=1, max_length=200)),
                ('ORDER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_name', models.CharField(max_length=200)),
                ('P_image', models.CharField(max_length=200)),
                ('Price', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.CharField(max_length=200)),
                ('R_date', models.DateField()),
                ('CUSTOMER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Customer')),
                ('PRODUCT', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_quantity', models.BigIntegerField()),
                ('PRODUCT', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('CATEGORY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Category')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='SUB_CATEGORY',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Sub_category'),
        ),
        migrations.AddField(
            model_name='employee',
            name='LOGIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Login'),
        ),
        migrations.AddField(
            model_name='customer',
            name='LOGIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Login'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='CUSTOMER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Customer'),
        ),
        migrations.AddField(
            model_name='cart',
            name='ORDER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Order'),
        ),
        migrations.AddField(
            model_name='cart',
            name='PRODUCT',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Product'),
        ),
        migrations.AddField(
            model_name='allocate',
            name='EMPLOYEE',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Employee'),
        ),
        migrations.AddField(
            model_name='allocate',
            name='ORDER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Order'),
        ),
    ]
