# Generated by Django 2.0.3 on 2024-04-08 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_name', models.CharField(max_length=200)),
                ('E_image', models.CharField(max_length=200)),
                ('E_address', models.CharField(max_length=200)),
                ('E_phn', models.BigIntegerField()),
                ('E_email', models.CharField(max_length=200)),
                ('gender', models.CharField(default=1, max_length=200)),
                ('LOGIN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Login')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='o_delivery',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
