# Generated by Django 2.0.3 on 2024-04-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20240408_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='o_delivery_boy',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
